// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const EXPECTED_SUPABASE_REF = "vuvdnmessgwhlggzcfqb";
const EXPECTED_SUPABASE_HOST = `${EXPECTED_SUPABASE_REF}.supabase.co`;

function pickSupabaseUrl(...candidates: Array<string | undefined>) {
  const valid = candidates.filter((url): url is string => /^https:\/\//.test(url ?? ""));
  return valid.find(url => url.includes(EXPECTED_SUPABASE_HOST)) ?? valid[0] ?? "";
}

const SUPABASE_URL = pickSupabaseUrl(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.SUPABASE_URL,
);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLIC_ANON_KEY ??
  import.meta.env.SUPABASE_ANON_KEY;
const isConfigured = /^https:\/\//.test(SUPABASE_URL ?? "") && Boolean(SUPABASE_PUBLISHABLE_KEY);

const isPreview = typeof window !== "undefined" && window.location.hostname.includes("-git-");
if (import.meta.env.DEV || isPreview) {
  console.info("[Supabase configuration]", {
    urlUsesHttps: /^https:\/\//.test(SUPABASE_URL ?? ""),
    publishableKeyPresent: Boolean(SUPABASE_PUBLISHABLE_KEY),
    isConfigured,
  });
}

export const supabaseConfig = { isConfigured };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// A syntactically valid fallback keeps React renderable when a deployment misses
// its VITE variables. AuthContext then resolves to the login screen instead of a blank page.
export const supabase = createClient<Database>(
  isConfigured ? SUPABASE_URL : "https://invalid.supabase.co",
  isConfigured ? SUPABASE_PUBLISHABLE_KEY : "invalid-publishable-key",
  {
  db: {
    schema: "public",
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
